parameters:
  clickandmortar.connector.job.job_parameters.default_values_provider.add_rekognition_data_mass_edit.class: ClickAndMortar\AkeneoRekognitionBundle\Connector\Job\JobParameters\DefaultValuesProvider\AddRekognitionDataMassEdit
  clickandmortar.connector.job_name.add_rekognition_data: 'add_rekognition_data'

services:
  clickandmortar.job.add_rekognition_data:
    class: '%pim_connector.job.simple_job.class%'
    arguments:
      - '%clickandmortar.connector.job_name.add_rekognition_data%'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - [ '@clickandmortar.step.add_rekognition_data.mass_edit' ]
    tags:
      -
        name: akeneo_batch.job
        connector: '%pim_enrich.connector_name.mass_edit%'
        type: '%pim_enrich.job.mass_edit_type%'

  clickandmortar.job.default_values_provider.add_rekognition_data:
    class: '%clickandmortar.connector.job.job_parameters.default_values_provider.add_rekognition_data_mass_edit.class%'
    arguments:
      - [ '%clickandmortar.connector.job_name.add_rekognition_data%' ]
    tags:
      - { name: akeneo_batch.job.job_parameters.default_values_provider }

  clickandmortar.job.constraint_collection_provider.add_rekognition_data:
    class: '%pim_enrich.connector.job.job_parameters.constraint_collection_provider.product_mass_edit.class%'
    arguments:
      - [ '%clickandmortar.connector.job_name.add_rekognition_data%' ]
    tags:
      - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
