services:
  clickandmortar.step.add_rekognition_data.mass_edit:
    class: '%pim_connector.step.item_step.class%'
    arguments:
      - 'perform'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_enrich.reader.database.product_and_product_model'
      - '@clickandmortar.connector.processor.mass_edit.product.add_rekognition_data'
      - '@pim_enrich.writer.database.product_and_product_model_writer'
